# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title A Gibbs sampler using Rcpp
#' @name gibbsC
#' @description A Gibbs sampler using Rcpp
#' @importFrom stats rnorm rgamma
#' @useDynLib SA24204180
#' @param N the number of samples
#' @param thin the number of between-sample random numbers
#' @return a random sample of size \code{n}
#' @examples
#' \dontrun{
#' rnC <- gibbsC(100,10)
#' par(mfrow=c(2,1));
#' plot(rnC[,1],type='l')
#' plot(rnC[,2],type='l')
#' }
#' @export
gibbsC <- function(N, thin) {
    .Call('_SA24204180_gibbsC', PACKAGE = 'SA24204180', N, thin)
}

#' @title A Linear regression using Rcpp
#' @name lrC
#' @description A Linear regression using Rcpp
#' @importFrom stats rnorm rgamma
#' @useDynLib SA24204180
#' @param x A numeric vector of independent variable values.
#' @param y A numeric vector of dependent variable values.
#' @return A list containing the intercept and slope of the regression line.
#' @examples
#' \dontrun{
#' y=ax+b
#' result<-lrC(x,y)
#' result["intercept"] = b
#' result["slope"] = a
#' }
#' @export
lrC <- function(x, y) {
    .Call('_SA24204180_lrC', PACKAGE = 'SA24204180', x, y)
}

